# Generated by Django 3.0.6 on 2020-05-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200510_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='MyBlock', max_length=100),
        ),
    ]
